version: '3.8'

services:
  web:
    image: adrianrp1988/ocsinventory-notify-service:1.0
    build: ./build
    container_name : ocsinventory-notify-service
    volumes:
      - ./data:/app/data
    expose:
      - 80
    networks:
      - services

networks:
  services:
    external: true
